services:
  - type: web
    name: nyuklabot
    runtime: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: BOT_TOKEN
        sync: false          # Render dashboard dan qo'shasiz
      - key: ADMIN_IDS
        sync: false          # Masalan: 123456789,987654321
      - key: CHANNEL_ID
        sync: false          # Masalan: @mychannel yoki -1001234567890
      - key: CHANNEL_LINK
        sync: false          # Masalan: https://t.me/mychannel
      - key: WEBHOOK_URL
        sync: false          # Masalan: https://nyuklabot.onrender.com
      - key: PORT
        value: 8080
      - key: DOWNLOADS_DIR
        value: /tmp/nyuklabot_downloads
    healthCheckPath: /health
    autoDeploy: true
