services:
  - type: web
    name: nyuklabot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: OWNER_ID
        sync: false
      - key: REQUIRED_CHANNEL
        sync: false
      - key: WEBHOOK_URL
        sync: false
      - key: PORT
        value: 8443
    healthCheckPath: /health
